#!/bin/sh
set -e

APP_DIR="/var/www/pinakes"
ENV_FILE="${APP_DIR}/.env"

# ---------------------------------------------------------------------------
# Generate .env from environment variables if it doesn't already exist
# (A bind-mounted .env takes precedence and skips this block)
# ---------------------------------------------------------------------------
if [ ! -f "$ENV_FILE" ]; then
    echo ">> No .env found — generating from environment variables …"

    cat > "$ENV_FILE" <<EOF
# Auto-generated by docker-entrypoint.sh
DB_HOST=${DB_HOST:-mariadb}
DB_USER=${DB_USER:-pinakes}
DB_PASS=${DB_PASS:-pinakes}
DB_NAME=${DB_NAME:-pinakes}
DB_PORT=${DB_PORT:-3306}
DB_SOCKET=

APP_ENV=${APP_ENV:-production}
APP_DEBUG=${APP_DEBUG:-false}
APP_LOCALE=${APP_LOCALE:-en_US}
APP_CANONICAL_URL=${APP_CANONICAL_URL:-}

DISPLAY_ERRORS=false
FORCE_HTTPS=false

PLUGIN_ENCRYPTION_KEY=${PLUGIN_ENCRYPTION_KEY:-$(php -r "echo 'base64:' . base64_encode(random_bytes(32));")}

SESSION_LIFETIME=${SESSION_LIFETIME:-3600}
EOF

    chown www-data:www-data "$ENV_FILE"
    chmod 640 "$ENV_FILE"
    echo ">> .env created."
fi

# ---------------------------------------------------------------------------
# Ensure writable directories exist with correct ownership
# ---------------------------------------------------------------------------
for dir in storage/backups storage/cache storage/calendar storage/logs \
           storage/plugins storage/sessions storage/tmp storage/uploads \
           public/uploads; do
    mkdir -p "${APP_DIR}/${dir}"
done
chown -R www-data:www-data "${APP_DIR}/storage" "${APP_DIR}/public/uploads"

# ---------------------------------------------------------------------------
# Wait for the database to be reachable
# ---------------------------------------------------------------------------
echo ">> Waiting for database at ${DB_HOST:-mariadb}:${DB_PORT:-3306} …"
max_tries=30
count=0
until php -r "
    \$h = '${DB_HOST:-mariadb}';
    \$p = (int)'${DB_PORT:-3306}';
    @\$c = new mysqli(\$h, '${DB_USER:-pinakes}', '${DB_PASS:-pinakes}', '', \$p);
    if (\$c->connect_error) exit(1);
    \$c->close();
" 2>/dev/null; do
    count=$((count + 1))
    if [ "$count" -ge "$max_tries" ]; then
        echo ">> ERROR: Could not connect to database after ${max_tries} attempts." >&2
        exit 1
    fi
    sleep 2
done
echo ">> Database is reachable."

# ---------------------------------------------------------------------------
# Auto-run the web installer check:
# If the database is empty (no 'libri' table), leave the installer accessible.
# The user completes setup via the browser at /installer/
# ---------------------------------------------------------------------------
table_exists=$(php -r "
    \$c = new mysqli('${DB_HOST:-mariadb}', '${DB_USER:-pinakes}', '${DB_PASS:-pinakes}', '${DB_NAME:-pinakes}', (int)'${DB_PORT:-3306}');
    if (\$c->connect_error) { echo '0'; exit; }
    \$r = \$c->query(\"SHOW TABLES LIKE 'libri'\");
    echo \$r && \$r->num_rows > 0 ? '1' : '0';
    \$c->close();
" 2>/dev/null)

if [ "$table_exists" = "0" ]; then
    echo ">> Database is empty — complete setup via the web installer at /installer/"
fi

# ---------------------------------------------------------------------------
# Hand off to php-fpm (or whatever CMD was passed)
# ---------------------------------------------------------------------------
exec "$@"
